### ISSUE TITLE
botan config returns wrong linker flags

### ISSUE THREAD

**Issue by christianix** [Rohde-Schwarz-Cybersecurity/botan#1]
The botan configuration tool mentioned in the documentation returns wrong linker flags:
```
> botan config libs
-lbotan-2.0 -lrt
```
However, libbotan-2.0.so does not exist.

Using package config instead returns correct linker flags:
```
> pkg-config --libs botan-2
-L/usr/local/lib -lbotan-2 -fstack-protector -m64 -pthread
```

**Comment by securitykernel** [comment]
Thanks for raising this issue and sorry for the overly long response time. This issue was already fixed upstream in https://github.com/randombit/botan/commit/f454713cf14c68929975fba07940284cac902a84 and will also be fixed in the next version released here.

**Comment by securitykernel** [comment]
Version 2.4.0-RSCS1 is released, which includes the fix from upstream.
