### ISSUE TITLE
Broken links in readme.rst

### ISSUE THREAD

**Issue by Killerhaschen** [Rohde-Schwarz-Cybersecurity/botan#3]
Botan: Crypto and TLS for C++11
- The links to 02102-1, 02102-2 and 03111 are broken and lead to a 404 page.
- Also the link to the project links to https://botan.randombit.org/ and not to teir porject page https://botan.randombit.net/

Release Downloads
- links to key and cert lead to https://www.rohde-schwarz.com/solutions/cybersecurity/overview/cybersecurity-solutions-overview_253768.html?change_c=true

BSI Compliant Usage of Botan
- TLS: The link to 02102-2 is  broken and leads to a 404 page.
- Random Number Generation: HMAC_DRBG

**Comment by securitykernel** [comment]
Will fix that soon, thank you for noticing.
